name: Build
on:
  push:
    branches: [naive]
    paths-ignore: [README.md]
  release:
    types: [created]
defaults:
  run:
    shell: bash
jobs:
  build_caddy_with_naive:
    runs-on: ubuntu-22.04
    env:
      BUNDLE: caddy-forwardproxy-naive-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.21.9
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: Build Caddy for ARM64
        run: |
          GOARCH=arm64 CGO_ENABLED=0 ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@master=$PWD
      - name: Pack naiveproxy assets
        run: |
          mkdir ${{ env.BUNDLE }}
          cp caddy LICENSE README.md ${{ env.BUNDLE }}
          tar cJf ${{ env.BUNDLE }}.tar.xz ${{ env.BUNDLE }}
          openssl sha256 ./caddy >sha256sum.txt
          echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >>$GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUNDLE }}.tar.xz caddy executable sha256 ${{ env.SHA256SUM }}
          path: sha256sum.txt
      - name: Generate release tag
        if: github.event_name == 'push'
        run: echo "RELEASE_TAG=build-arm64-$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.BUNDLE }}.tar.xz
          tag_name: ${{ github.event_name == 'release' && github.ref_name || env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
